### ISSUE TITLE
Can't figure out how to work with associations 

### ISSUE THREAD

**Issue by Reak45** [suksant/sequelize-typescript-examples#3]
Could you please provide full, working example of how to deal with associations? From start to finish. I have already spend days on figuring it out but with no success. I am begging.

**Comment by suksant** [comment]
An example of how you define associate in the model is like this:
```
export default function(sequelize: Sequelize, dataTypes: DataTypes):
  SequelizeStatic.Model<ModelAInstance, ModelAAttributes> {
  let ModelA = sequelize.define<ModelAInstance, ModelAAttributes>("ModelA", {
    name: {type: dataTypes.STRING, allowNull: false, primaryKey: true},
    description: {type: dataTypes.TEXT, allowNull: true}
  }, {
    indexes: [],
    classMethods: {
      associate: (models: Models) => {
        ModelA.belongsTo(models.ModelB, {
          foreignKey: "modelBAttr",
          targetKey: "modelBAttr"
        });
      }
    },
    timestamps: false
  });

  return ModelA;
```
In TypeScript, Sequelize or any ORM can be a bit of a pain when trying to create a perfect type definition for models. I'm sorry, but I don't have a full example at the moment due to tight schedules. I'm sure Sequelize people would gladly help.

**Comment by suksant** [comment]
#1 is also related.
